#!/usr/bin/env bash
cd `dirname $0`

source virtualenvwrapper.sh

function check_worked {
    if ! $*
    then
        exit 1
    fi
}

check_worked pandoc -f markdown -t rst README.markdown > README
check_worked python3 setup.py sdist upload
rm -r dist django_async.egg-info README
