#!/usr/bin/env bash
cd `dirname $0`

source virtualenvwrapper.sh

# virtualenvwrapper doesn't work with "set -e
function check_worked {
    if ! $*
    then
        exit 1
    fi
}

workon async_1.9
cd test-projects/django_1_9
echo Django 1.9
check_worked python manage.py test async
check_worked pylint --rcfile=../../pylintrc --output-format=colorized ../../async

workon async_1.10
cd ../django_1_10
echo Django 1.10
check_worked python manage.py test async

workon async_1.11
cd ../django_1_11
echo Django 1.11
check_worked python manage.py test async

workon async_1.3
cd ../django_1_3
echo Django 1.3
check_worked python -tt manage.py test async

workon async_1.8
cd ../django_1_8
echo Django 1.8
check_worked python manage.py test async

workon async_1.7
cd ../django_1_7
echo Django 1.7
check_worked python manage.py test async

workon async_1.4
cd ../django_1_4
echo "Django 1.4 (USE_TZ=False)"
check_worked python manage.py test async
echo "Django 1.4 (USE_TZ=True)"
check_worked python manage.py test --settings=django_1_4.settings.usetz async

workon async_1.0
cd ../django_1_0
echo "Django 1.0"
check_worked python manage.py test d1
