#!/usr/bin/env bash
cd `dirname $0`

source virtualenvwrapper.sh

# virtualenvwrapper doesn't work with "set -e
function check_worked {
    if ! $*
    then
        exit 1
    fi
}

workon async_1.3
cd test-projects/django_1_3
echo Django 1.3
check_worked python -tt manage.py test async

cd ../..
check_worked pylint --rcfile=pylintrc --output-format=colorized async

workon async_1.4
cd test-projects/django_1_4
export REUSE_DB=1
echo "Django 1.4 (USE_TZ=False)"
check_worked python manage.py test async
echo "Django 1.4 (USE_TZ=True)"
check_worked python manage.py test --settings=django_1_4.settings.usetz async
