#!/bin/bash
cd `dirname $0`

export PYTHONPATH=${PYTHONPATH}:../..
GIVEN_MODULE=$1
MODULE=${GIVEN_MODULE:="async_exec"}
echo "running test on $MODULE"
python ./manage.py test $MODULE \
    --with-coverage --cover-erase --cover-package=async_exec
